language: go
arch:
  - amd64
  - ppc64le
go:
  - 1.2.x
  - 1.3.x
  - 1.4.x
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip
jobs:
 exclude: # Excluded for power support as the lower versions are not supported
  - arch: ppc64le
    go: 1.2.x
  - arch: ppc64le
    go: 1.3.x
  - arch: ppc64le
    go: 1.4.x
